name: Continuous Deployment Practice

on: [push]

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      run: |
        export AWS_ACCESS_KEY_ID={{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY={{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Run 
      env:
        IP: 127.0.0.1  # 자신의 아이피로 변경합니다.
      run: |
        aws s3 cp index.html s3://workshop-practices/$(IP) --acl public-read
